### ISSUE TITLE
Entities Not Appearing After Setup

### ISSUE THREAD

**Issue by philidinator** [soloam/ha-fireflyiii-integration#25]
Hello,

First of all, thanks for the awesome integration! I've always managed with the REST API & sensors previously. Then I came across this through the FireFly discussions.

The setup assistant completes successfully, but afterwards no entities appear. The following error is logged:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii_coordinator.py", line 257, in _async_update_data
    await data_list.gather()
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii_objects.py", line 251, in gather
    result = await gather(*[res for res in self._coroutines])
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii.py", line 744, in bills
    if not isinstance(transaction, FireflyiiiTransaction):
UnboundLocalError: cannot access local variable 'transaction' where it is not associated with a value

```

Any help in resolving this would be greatly appreciated!

Thank you!

**Comment by soloam** [comment]
This looks like a coding error, i'll look at it and report back, thank you

**Comment by soloam** [comment]
I found the problem, tks for the report! I'll fix it as quickly as possible! For now, if you you would like to pull other data, try to remove the integration from HA (only HA, not HACS) and when setting up, uncheck Bills!

**Comment by soloam** [comment]
FIxed with #26 Check release 1.0.1

**Comment by OvernightPancake** [comment]
I am also facing a similar issue, this time whenever budgets are selected:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii_coordinator.py", line 257, in _async_update_data
    await data_list.gather()
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii_objects.py", line 251, in gather
    result = await gather(*[res for res in self._coroutines])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fireflyiii_integration/integrations/fireflyiii.py", line 624, in budgets
    limit_attributes = budget_limit.get("attributes", {})
                       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'budget_limit' where it is not associated with a value`

Otherwise, when I deselect budgets, I do not seem to have any issues.

**Comment by soloam** [comment]
Tks for the report @OvernightPancake , this is a different problem! I'll fix it as soon as possible!
